### PR TITLE
Add example option for proxy and external_downloader

### PR DESCRIPTION
**Pull request by blueberry-maker**
I had to create a dummy account for this PR.

My real account got like 20k star and 1.5k follower

Haha

### CODE REVIEW

**Comment by blueberry-maker** [comment]
I am not sure edit `poetry.lock` is the correct way to update version.
I am familiar with Gemfile in ruby
but not Poetry in Python

**Comment by blueberry-maker** [comment]
image

**Comment by Nukesor** [comment]
Damn. I somehow completely oversaw this PR. Sorry mate.

pypoetry.lock is the wrong way to update `youtube-dl`. The file you're looking for is `pyproject.toml`
Update the file, run `poetry update`. All dependencies should be updated to the newest version and the lock file should update :)

**Comment by Nukesor** [comment]
Closing for now.
All dependencies have been adjusted in a separate commit.

Feel free to re-open the PR, but it would be awesome to also get a Commandline option for this.

**Pull request closed without merging**
